---
services: docker

language: python
python:
  - 3.6
cache: pip

install:
  - pip install ansible==2.7.8 molecule docker

before_script:
  - cd ..
  - mv ansible-role-my-shell hadrienpatte.my_shell
  - cd hadrienpatte.my_shell

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
