---
- name: Install ansible
  pip:
    name: ansible
    state: present
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/a"
    virtualenv_command: "{{ ansible_env.HOME }}/.local/bin/virtualenv"
    virtualenv_python: python3
...
