---
- name: Configure bash autocompletion
  become: true
  get_url:
    url: https://raw.githubusercontent.com/{{ item.file }}
    dest: /etc/bash_completion.d/{{ item.name }}
  loop:
    - name: docker-compose
      file: docker/compose/1.24.0/contrib/completion/bash/docker-compose
    - name: complete-alias
      file: cykerway/complete-alias/master/bash_completion.sh
...
