---
- name: Create .bashrc.d directory
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/"
    state: directory

- name: Clone the Awesome Ultimate Vim configuration
  git:
    clone: true
    repo: https://github.com/amix/vimrc.git
    dest: "{{ ansible_env.HOME }}/.vim_runtime"
    depth: 1
    version: master

- name: Copy dotfiles
  copy:
    src: "{{ item }}.sh"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  loop:
    - bashrc
    - bash_colors
    - inputrc
    - vimrc
    - bashrc.d/autojump
    - bashrc.d/pipenv
    - bashrc.d/virtualenvwrapper
    - bashrc.d/pipenvwrapper
    - bashrc.d/undistract-me
    - bashrc.d/bash_git_prompt

- name: Configure bash aliases
  template:
    src: bash_aliases.j2
    dest: "{{ ansible_env.HOME }}/.bash_aliases"

- name: Configure sudo insults
  become: true
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults        insults
    insertafter: ^Defaults
    line: Defaults        insults
    validate: /usr/sbin/visudo -cf %s
...
