---
- name: Create .bashrc.d directory
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d/"
    state: directory

- name: Copy dotfiles
  copy:
    src: "{{ item }}.sh"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  loop:
    - bashrc
    - bash_colors
    - bash_aliases
    - inputrc
    - bashrc.d/autojump
    - bashrc.d/pipenv
    - bashrc.d/virtualenvwrapper
    - bashrc.d/pipenvwrapper
    - bashrc.d/bash_git_prompt

- name: Configure sudo insults
  become: true
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults        insults
    insertafter: ^Defaults
    line: Defaults        insults
    validate: /usr/sbin/visudo -cf %s
...
