---
- name: Download base hosts file
  become: true
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/hosts

- name: Add localhost
  become: true
  lineinfile:
    path: /etc/hosts
    insertafter: "# Custom host records are listed here."
    regexp: ^127.0.1.1 {{ ansible_hostname }}
    line: 127.0.1.1 {{ ansible_hostname }}

- name: Add hosts from inventory
  become: true
  lineinfile:
    path: /etc/hosts
    insertafter: "# Custom host records are listed here."
    regexp: ^{{ hostvars[item].ansible_host }} {{ item }}
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  loop: "{{ groups.all | sort }}"
  when: hostvars[item].ansible_host is defined
...
