---
- name: Add public keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/debian/gpg
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://packages.microsoft.com/keys/microsoft.asc
  register: apt_key_result
  retries: 3
  until: apt_key_result is succeeded

- name: Add repositories
  become: true
  apt_repository:
    repo: deb {{ item }}
    state: present
  loop:
    - >
      [arch=amd64] https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    - https://packages.cloud.google.com/apt cloud-sdk main
    - >
      [arch=amd64] https://packages.microsoft.com/repos/azure-cli/
      {{ ansible_distribution_release }} main

- name: Install apt packages
  become: true
  apt:
    update_cache: true
    name:
      - git
      - vim
      - htop
      - ncdu
      - nmap
      - sshuttle
      - p7zip-full
      - gnupg2
      - unrar
      - sl
      - cmatrix
      - cowsay
      - traceroute
      - autojump
      - python3-dev
      - python-setuptools  # Required to use ansible pip module
      - undistract-me
      - docker-ce
      - docker-compose
      - bash-completion
      - google-cloud-sdk
      - azure-cli
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3

- name: Download get-pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  delegate_to: localhost

- name: Install pip
  script: /tmp/get-pip.py --user
  args:
    executable: python3
    creates: "{{ ansible_env.HOME }}/.local/bin/pip"

- name: Install pip packages
  pip:
    name:
      - pipenv
      - virtualenvwrapper
      - awscli
    state: present
    executable: "{{ ansible_env.HOME }}/.local/bin/pip3"
    extra_args: --user

- name: Install pipenvwrapper
  get_url:
    url: "https://raw.githubusercontent.com/Peibolvig/pipenvwrapper/master/\
      pipenvwrapper.sh"
    dest: "{{ ansible_env.HOME }}/.local/bin/pipenvwrapper.sh"
    mode: 0755

- name: Start and enable docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

...
