---
- name: Add Google Cloud public key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  register: apt_key_result
  retries: 3
  until: apt_key_result is succeeded

- name: Add Google Cloud repository
  become: true
  apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/cloud.google.gpg]
      https://packages.cloud.google.com/apt
      cloud-sdk-{{ ansible_distribution_release }} main
    state: present

- name: Install kubectl
  become: true
  apt:
    update_cache: true
    name: kubectl
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Install kube-ps1
  get_url:
    url: https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
    dest: "{{ ansible_env.HOME }}/.bashrc.d/kube-ps1"

- name: Install kubectx and kubens
  become: true
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: 0755
  loop:
    - kubectx
    - kubens

- name: Find latest stern version
  uri:
    url: https://api.github.com/repos/wercker/stern/releases
    return_content: true
  register: stern_response

- name: Install stern
  become: true
  get_url:
    url: "{{ stern_response.json[0].assets[1].browser_download_url }}"
    dest: /usr/local/bin/stern
    mode: 0755

- name: Find latest k9s version
  uri:
    url: https://api.github.com/repos/derailed/k9s/releases
    return_content: true
  register: k9s_response

- name: Install k9s
  become: true
  unarchive:
    src: "{{ k9s_response.json[0].assets[3].browser_download_url }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
    owner: root
    group: root
    exclude:
      - LICENSE
      - README.md

- name: Find latest helm version
  uri:
    url: https://api.github.com/repos/helm/helm/releases
    return_content: true
  register: helm_response

- name: Install helm
  become: true
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_response.json[0].tag_name }}\
      -linux-amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
    owner: root
    group: root
    exclude:
      - LICENSE
      - README.md
      - tiller
    extra_opts:
      - --transform
      - s/linux-amd64\///

- name: Find latest oc version
  uri:
    url: https://api.github.com/repos/openshift/origin/releases
    return_content: true
  register: oc_response

- name: Install oc
  become: true
  unarchive:
    src: "{{ oc_response.json[0].assets[1].browser_download_url }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: 0755
    owner: root
    group: root
    exclude:
      - LICENSE
      - README.md
      - kubectl
    extra_opts:
      - --transform
      - "s/{{ oc_response.json[0].assets[1].name[:-7] }}\\///"
...
