---
- name: Add Google Cloud public key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  register: apt_key_result
  retries: 3
  until: apt_key_result is succeeded

- name: Add Google Cloud repository
  become: true
  apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/cloud.google.gpg]
      https://packages.cloud.google.com/apt
      cloud-sdk-{{ ansible_distribution_release }} main
    state: present

- name: Install kubectl
  become: true
  apt:
    update_cache: true
    name: kubectl
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Install kube-ps1
  get_url:
    url: https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
    dest: "{{ ansible_env.HOME }}/.bashrc.d/kube-ps1"

- name: Install kubectx and kubens
  become: true
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: 0755
  loop:
    - kubectx
    - kubens

- name: Install stern
  become: true
  get_url:
    url: "https://github.com/wercker/stern/releases/download/\
      {{ my_shell_stern_version }}/stern_linux_amd64"
    dest: /usr/local/bin/stern
    mode: 0755
...
