---
- name: Install packages
  include_tasks: install.yml

- name: Configure git
  include_tasks: git.yml

- name: Configure bash
  include_tasks: bash.yml

- name: Install and configure sshrc
  include_tasks: sshrc.yml
...
