---
- name: Install CLI utilities
  become: true
  apt:
    update_cache: true
    name:
      - git
      - vim
      - htop
      - ncdu
      - nmap
      - sshuttle
      - p7zip-full
      - gnupg2
      - unrar
      - sl
      - cmatrix
      - cowsay
      - traceroute
      - autojump
    state: present

- name: Copy .bashrc
  copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: 0600

- name: Copy .bash_colors
  copy:
    src: bash_colors
    dest: "{{ ansible_env.HOME }}/.bash_colors"

- name: Copy .inputrc
  copy:
    src: inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
...
