---
- name: Install CLI utilities
  become: true
  apt:
    update_cache: true
    name:
      - git
      - vim
      - htop
      - ncdu
      - nmap
      - sshuttle
      - p7zip-full
      - gnupg2
      - unrar
      - sl
      - cmatrix
      - cowsay
      - traceroute
      - autojump
      - python3-dev
      - python-setuptools  # Required to use ansible pip module
    state: present
  register: apt_result
  until: apt_result is succeeded
  retries: 3

- name: Download get-pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  delegate_to: localhost

- name: Install pip
  script: /tmp/get-pip.py --user
  args:
    executable: python3
    creates: "{{ ansible_env.HOME }}/.local/bin/pip"

- name: Copy .bashrc
  copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: 0600

- name: Copy .bash_colors
  copy:
    src: bash_colors
    dest: "{{ ansible_env.HOME }}/.bash_colors"

- name: Copy .inputrc
  copy:
    src: inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"

- name: Configure sudo insults
  become: true
  lineinfile:
    path: /etc/sudoers
    regexp: ^Defaults        insults
    insertafter: ^Defaults
    line: Defaults        insults
    validate: /usr/sbin/visudo -cf %s
...
