---
- name: Create .ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh/"
    state: directory

- name: Create ssh config file
  template:
    src: ssh_config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
...
