---
- name: Install shell utilities and deploy various dotfiles
  hosts: all
  roles:
    - role: hadrienpatte.my_shell
  vars:
    ansible_user: test-user
    ansible_env:
      HOME: /home/test-user
    my_shell_git_key_fingerprint: 0123456789ABCDEF0123456789ABCDEF01234567
...
