PIPENVWRAPPER=$HOME/.local/bin/pipenvwrapper.sh
if [ -f $PIPENVWRAPPER ]; then
    WORKON_HOME=$HOME/.virtualenvs
    PROJECT_HOME=$HOME/Documents/Projets
    # PIPENVWRAPPER_USE_VIRTUALENVWRAPPER_FUNCTION_NAMES=1
    . $PIPENVWRAPPER
fi
unset PIPENVWRAPPER
